### ISSUE TITLE
Rename config.js to config.js.example

### ISSUE THREAD

**Issue by netfone** [flexzero/orbita-backend#2]
I think we have to ignore `config.js` file from the repo, instead rename it to`config.js.example`, for security purposes. We may accidentally commit values from this config file.

**Comment by flexzero** [comment]
yes it's just for temporary purpose, once the software progresses we can use the different robust mechanism for retrieving config e.g we can store config in server's environment variables

**Comment by flexzero** [comment]
for now let's remove it

**Comment by flexzero** [comment]
there are other things to consider, for now i'm using persistent storage for the storing the access_token that's also an security issue, it will be moved to the database in future

**Comment by netfone** [comment]
just add config.js.example. but don't add real values tho. so we know what are in the config.js.

**Comment by flexzero** [comment]
config has been moved to .env
